name: Do tickets stuff
on: 
  issues:
    types: 
      - opened
jobs: 
  automation: 
    runs-on: ubuntu-latest
    steps: 
    - name: Add issues to project
      uses: actions/add-to-project@v0.0.5
      with: 
        project-url: https://github.com/users/sabinmarcu/projects/1/views/1
        github-token: ${{ secrets.PROJECT_PAT }}